env:
  browser: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - jest
  - import
ignorePatterns:
  - docs
rules:
  no-console: ["error", { allow: ["info", "warn", "error"] }]
  import/extensions: [error, ignorePackages, { ts: never, js: never }]
  import/prefer-default-export: off
