version: '3'
services:
  node:
    image: node:18.16.0-alpine3.16
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 9000:9000
    command: ["yarn", "start"]
volumes:
  node_modules:
    driver: local
