name: eslint
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  eslint_npm:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - name: pronto run
        uses: HeRoMo/pronto-action@v1.57.0
        with:
          runner: eslint_npm
