name: jest
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: coverage
