name: jest
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'yarn'
      - run: yarn install
      - uses: actions/cache@v3
        with:
          path: ./test/fixtures/shape_files
          key: ${{ runner.os }}-${{ hashFiles('./test/fixture_config.ts') }}-fixtures_shape_files
      - run: yarn test
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: coverage
